[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_BASE_URL,NEXT_PUBLIC_PAYPAL_CLIENT_ID,NEXT_PUBLIC_PAYPAL_USERNAME,NEXT_PUBLIC_UPI_ID"

[[plugins]]
  package = "@netlify/plugin-nextjs"
